version: '3.8'

services:
  # SERVICIO 1: Tu página web (PHP)
  web:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db
    links:
      - db

  # SERVICIO 2: La base de datos (MariaDB)
  db:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root        # Contraseña maestra
      MYSQL_DATABASE: info_clientes    # Nombre de tu DB
    volumes:
      # AQUÍ ESTÁ LA MAGIA:
      # Copia tu archivo sql.sql local a la carpeta de inicio de la DB
      - ./sql.sql:/docker-entrypoint-initdb.d/init.sql
